apiVersion: v1
kind: Service
metadata:
  name: gva-server
  annotations:
    jny/develop-manage: backend
    github: "https://devops-manage.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gva-server
    version: gva-vue3
spec:
  selector:
    app: gva-server
    version: gva-vue3
  ports:
    - port: 8888
      name: http
      targetPort: 8888
  type: ClusterIP
#  type: NodePort
